### PR TITLE
docs: pure javascript markedHighlight documentation

### PR DESCRIPTION
**Pull request by storytellerF**
#58

### CODE REVIEW

**Comment by storytellerF** [comment]
hold on

**Comment by storytellerF** [comment]
now is right.
Should use `const {markedHighlight} = this.markedHighlight;`

**Comment by UziTech** [comment]
It should probably be `window.markedHighlight` or `globalThis.markedHighlight` `this` can be anything depending on where it is called.

**Comment by storytellerF** [comment]
> It should probably be `window.markedHighlight` or `globalThis.markedHighlight` `this` can be anything depending on where it is called.

I have changed it to **globalThis**.

**Comment by UziTech** [comment]
Thanks for doing this!

**Pull request merged**
